# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projekt_2_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Projekt_2DialogBase(object):
    def setupUi(self, Projekt_2DialogBase):
        Projekt_2DialogBase.setObjectName("Projekt_2DialogBase")
        Projekt_2DialogBase.resize(553, 470)
        self.button_box = QtWidgets.QDialogButtonBox(Projekt_2DialogBase)
        self.button_box.setGeometry(QtCore.QRect(200, 430, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.label_dh_select = QtWidgets.QLabel(Projekt_2DialogBase)
        self.label_dh_select.setGeometry(QtCore.QRect(50, 40, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dh_select.setFont(font)
        self.label_dh_select.setObjectName("label_dh_select")
        self.label_dh_result = QtWidgets.QLabel(Projekt_2DialogBase)
        self.label_dh_result.setGeometry(QtCore.QRect(320, 100, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dh_result.setFont(font)
        self.label_dh_result.setText("")
        self.label_dh_result.setObjectName("label_dh_result")
        self.pushButton_dh = QtWidgets.QPushButton(Projekt_2DialogBase)
        self.pushButton_dh.setGeometry(QtCore.QRect(40, 100, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_dh.setFont(font)
        self.pushButton_dh.setObjectName("pushButton_dh")
        self.mMapLayerComboBox = QgsMapLayerComboBox(Projekt_2DialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(220, 40, 281, 31))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.pushButton_pole = QtWidgets.QPushButton(Projekt_2DialogBase)
        self.pushButton_pole.setGeometry(QtCore.QRect(40, 160, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_pole.setFont(font)
        self.pushButton_pole.setObjectName("pushButton_pole")
        self.label_pole_result = QtWidgets.QLabel(Projekt_2DialogBase)
        self.label_pole_result.setGeometry(QtCore.QRect(330, 160, 171, 41))
        self.label_pole_result.setText("")
        self.label_pole_result.setObjectName("label_pole_result")
        self.checkBox_m2 = QtWidgets.QCheckBox(Projekt_2DialogBase)
        self.checkBox_m2.setGeometry(QtCore.QRect(50, 210, 81, 20))
        self.checkBox_m2.setObjectName("checkBox_m2")
        self.checkBox_ary = QtWidgets.QCheckBox(Projekt_2DialogBase)
        self.checkBox_ary.setGeometry(QtCore.QRect(130, 210, 81, 20))
        self.checkBox_ary.setObjectName("checkBox_ary")
        self.checkBox_ha = QtWidgets.QCheckBox(Projekt_2DialogBase)
        self.checkBox_ha.setGeometry(QtCore.QRect(230, 210, 81, 20))
        self.checkBox_ha.setObjectName("checkBox_ha")
        self.label_h_error = QtWidgets.QLabel(Projekt_2DialogBase)
        self.label_h_error.setGeometry(QtCore.QRect(40, 300, 231, 51))
        self.label_h_error.setText("")
        self.label_h_error.setObjectName("label_h_error")
        self.label_pole_error = QtWidgets.QLabel(Projekt_2DialogBase)
        self.label_pole_error.setGeometry(QtCore.QRect(310, 300, 191, 51))
        self.label_pole_error.setText("")
        self.label_pole_error.setObjectName("label_pole_error")
        self.pushButton_clear = QtWidgets.QPushButton(Projekt_2DialogBase)
        self.pushButton_clear.setGeometry(QtCore.QRect(50, 380, 191, 61))
        self.pushButton_clear.setObjectName("pushButton_clear")

        self.retranslateUi(Projekt_2DialogBase)
        self.button_box.accepted.connect(Projekt_2DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(Projekt_2DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Projekt_2DialogBase)

    def retranslateUi(self, Projekt_2DialogBase):
        _translate = QtCore.QCoreApplication.translate
        Projekt_2DialogBase.setWindowTitle(_translate("Projekt_2DialogBase", "Projekt IG 2"))
        self.label_dh_select.setText(_translate("Projekt_2DialogBase", "Wybierz warstwę"))
        self.pushButton_dh.setText(_translate("Projekt_2DialogBase", "Oblicz różnicę wysokości"))
        self.pushButton_pole.setText(_translate("Projekt_2DialogBase", "Oblicz pole"))
        self.checkBox_m2.setText(_translate("Projekt_2DialogBase", "m^2"))
        self.checkBox_ary.setText(_translate("Projekt_2DialogBase", "ary"))
        self.checkBox_ha.setText(_translate("Projekt_2DialogBase", "ha"))
        self.pushButton_clear.setText(_translate("Projekt_2DialogBase", "Wyczysc wyniki"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Projekt_2DialogBase = QtWidgets.QDialog()
    ui = Ui_Projekt_2DialogBase()
    ui.setupUi(Projekt_2DialogBase)
    Projekt_2DialogBase.show()
    sys.exit(app.exec_())
