# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projekt_2_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Projekt_2DialogBase(object):
    def setupUi(self, Projekt_2DialogBase):
        Projekt_2DialogBase.setObjectName("Projekt_2DialogBase")
        Projekt_2DialogBase.resize(553, 470)
        self.button_box = QtWidgets.QDialogButtonBox(Projekt_2DialogBase)
        self.button_box.setGeometry(QtCore.QRect(200, 430, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.label_dh_select = QtWidgets.QLabel(Projekt_2DialogBase)
        self.label_dh_select.setGeometry(QtCore.QRect(50, 40, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dh_select.setFont(font)
        self.label_dh_select.setObjectName("label_dh_select")
        self.label_dh_result = QtWidgets.QLabel(Projekt_2DialogBase)
        self.label_dh_result.setGeometry(QtCore.QRect(320, 100, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dh_result.setFont(font)
        self.label_dh_result.setText("")
        self.label_dh_result.setObjectName("label_dh_result")
        self.pushButton_dh = QtWidgets.QPushButton(Projekt_2DialogBase)
        self.pushButton_dh.setGeometry(QtCore.QRect(40, 100, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_dh.setFont(font)
        self.pushButton_dh.setObjectName("pushButton_dh")
        self.mMapLayerComboBox = QgsMapLayerComboBox(Projekt_2DialogBase)
        self.mMapLayerComboBox.setGeometry(QtCore.QRect(220, 40, 281, 31))
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")

        self.retranslateUi(Projekt_2DialogBase)
        self.button_box.accepted.connect(Projekt_2DialogBase.accept) # type: ignore
        self.button_box.rejected.connect(Projekt_2DialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Projekt_2DialogBase)

    def retranslateUi(self, Projekt_2DialogBase):
        _translate = QtCore.QCoreApplication.translate
        Projekt_2DialogBase.setWindowTitle(_translate("Projekt_2DialogBase", "Projekt IG 2"))
        self.label_dh_select.setText(_translate("Projekt_2DialogBase", "Wybierz warstwę"))
        self.pushButton_dh.setText(_translate("Projekt_2DialogBase", "Oblicz różnicę wysokości"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Projekt_2DialogBase = QtWidgets.QDialog()
    ui = Ui_Projekt_2DialogBase()
    ui.setupUi(Projekt_2DialogBase)
    Projekt_2DialogBase.show()
    sys.exit(app.exec_())
